/**
 * What is actually serving each screen (ticket UC2-064).
 *
 * THE PROBLEM THIS SOLVES
 * -----------------------
 * The header carried one word for the whole board — `adapter.mode`, rendered as
 * LIVE or SIMULATED — and that word is wrong on every screen, because the board
 * is genuinely mixed and always has been.
 *
 * In the deployed build `VITE_DATA_MODE` is never set (the CI job does not pass
 * it), so the base adapter is the simulator and the chip reads SIMULATED. But
 * `VITE_CARGO_SOURCE` defaults to `poc3`, so Import, Export, Movements, CFS/ECY
 * and Data Quality are serving the real ingested corpus and say so on their own
 * `SourceBadge`. An evaluator reads SIMULATED in the header, then reads
 * "Data Source: ICEGATE · CHPOI03" two inches below it. One of them is lying and
 * they cannot tell which.
 *
 * Understating is not the safe direction either. Calling real customs documents
 * simulated throws away the strongest evidence in the bid.
 *
 * WHAT IT IS
 * ----------
 * A declarative map from tab to what serves it, evaluated against the runtime
 * configuration. Deliberately data, not React, so the guard test can assert it
 * against the adapter that actually does the delegating — see
 * `SIMULATOR_BACKED_READS`, and `test/provenance.test.ts` which reads
 * `poc3-cargo-adapter.ts` and fails if the two drift apart. A provenance map
 * maintained by hand is a provenance map that goes stale, and a stale one is
 * worse than none: it is a confident claim nobody re-checks.
 */
import type { TabId } from '../sim/scenarioPlayer.js';

/**
 * The `DataAdapter` reads `Poc3CargoAdapter` hands straight to the adapter below
 * it — i.e. the ones POC-3 does NOT re-source, which on a default build means
 * the simulator.
 *
 * ⚠ Kept in sync by `test/provenance.test.ts`, which extracts every
 * `return this.base.X` from the adapter source and demands this set matches. If
 * you make one of these real, the test fails until this list and the tab map
 * below are updated — which is the point.
 */
export const SIMULATOR_BACKED_READS = [
  'getFacilities',
  'getTerminals',
  'getGateOps',
  'getGateQueueForecast',
  'getPendency',
  'getRailSide',
  'getRakeForecast',
  'getITRHO',
  'getEmptyPool',
  'getKPIs',
  'getNotifications',
  'getIntegrationHealth',
  'runScenario',
] as const;

/** How a screen's data is produced. Ordered worst-to-best for summarising. */
export type Provenance =
  /** Held only in this browser — localStorage / BroadcastChannel. */
  | 'BROWSER'
  /** Generated by the schema-accurate simulator. No external system involved. */
  | 'SIMULATED'
  /** Some panels real, some simulated. The detail says which. */
  | 'MIXED'
  /** Served by a real backend over real ingested data. */
  | 'REAL'
  /** Fixed artefacts — exported model metrics, written methodology. */
  | 'STATIC';

export interface ScreenProvenance {
  tab: TabId;
  provenance: Provenance;
  /** One line an operator can read aloud. */
  summary: string;
  /** Named real parts, when MIXED. */
  real?: string;
  /** Named simulated parts, when MIXED. */
  simulated?: string;
}

/** The runtime facts the map is evaluated against. */
export interface ProvenanceContext {
  /** `VITE_CARGO_SOURCE` — poc3 | mock | reference. */
  cargoSource: string;
  /** `adapter.mode` — the base adapter, mock | live. */
  baseMode: string;
  /**
   * Whether any connector service answered its own /health. Null while the probe
   * is still in flight — rendered as "checking", never optimistically as live.
   */
  connectorsLive: boolean | null;
}

const POC3 = (c: ProvenanceContext) => c.cargoSource === 'poc3';

/**
 * Per-screen provenance.
 *
 * Every entry states the source in the terms the panel's own `SourceBadge` uses,
 * so the header and the panel can never disagree. Where a tab genuinely mixes
 * both — Gate has real terminal documents beside a simulated queue — it says
 * MIXED and names the halves rather than rounding to whichever is flattering.
 */
export function screenProvenance(ctx: ProvenanceContext): ScreenProvenance[] {
  const poc3 = POC3(ctx);
  const corpus = 'the ingested UC-II corpus, via POC-3';
  const sim = 'the schema-accurate simulator';

  return [
    {
      tab: 'import',
      provenance: poc3 ? 'REAL' : 'SIMULATED',
      summary: poc3
        ? `IGM, RMS scanning, Bill of Entry and E-DO from ${corpus}.`
        : `Cargo source is not POC-3, so the import registers come from ${sim}.`,
    },
    {
      tab: 'export',
      provenance: poc3 ? 'REAL' : 'SIMULATED',
      summary: poc3
        ? `Form 11, Shipping Bill, LEO, the EAL load list, COPRAR/COARRI and departures from ${corpus}.`
        : `Cargo source is not POC-3, so the export chain comes from ${sim}.`,
    },
    {
      // The honest awkward one. The documents are real records; the queue physics
      // are generated. Calling the whole tab either name would be false.
      tab: 'gate',
      provenance: poc3 ? 'MIXED' : 'SIMULATED',
      summary: poc3
        ? 'Real gate documents beside a simulated queue.'
        : `Everything on this tab comes from ${sim}.`,
      ...(poc3 ? {
        real: 'EIR, PIN tickets and CODECO gate-out messages',
        simulated: 'queue lengths, waiting times and the gate-queue forecast input',
      } : {}),
    },
    {
      tab: 'pendency',
      provenance: poc3 ? 'MIXED' : 'SIMULATED',
      summary: poc3
        ? 'Real published occupancy beside a simulated pendency breakdown.'
        : `Everything on this tab comes from ${sim}.`,
      ...(poc3 ? {
        real: 'JNPA Daily Status Report yard occupancy',
        simulated: 'the ageing bands and per-facility pendency counts',
      } : {}),
    },
    {
      // Not "under-fed" as a euphemism — there IS real rail data in the corpus
      // (CTO consignments, FOIS train intimations) and it has never been loaded.
      tab: 'rail',
      provenance: 'SIMULATED',
      summary: `Rake and siding movements come from ${sim}. `
        + 'The corpus holds real CTO rail consignments and FOIS train intimations; '
        + 'neither has been ingested, so none of it reaches this screen.',
    },
    {
      tab: 'itrho',
      provenance: 'SIMULATED',
      summary: `Inter-terminal movements come from ${sim}. No ITRHO feed is ingested.`,
    },
    {
      tab: 'empty',
      provenance: 'SIMULATED',
      summary: `Depot balances come from ${sim}. `
        + 'Real empty-container movements DO exist in the corpus (ECY-CODECO) — they '
        + 'feed the CFS/ECY tab, not this one.',
    },
    {
      tab: 'cfsecy',
      provenance: poc3 ? 'REAL' : 'SIMULATED',
      summary: poc3
        ? `CFS and ECY gate movements from ${corpus}.`
        : `Cargo source is not POC-3, so this comes from ${sim}.`,
    },
    {
      tab: 'movements',
      provenance: poc3 ? 'REAL' : 'SIMULATED',
      summary: poc3
        ? `The container register and its lifecycle events from ${corpus}.`
        : `Cargo source is not POC-3, so movements come from ${sim}.`,
    },
    {
      tab: 'scenarios',
      provenance: 'SIMULATED',
      summary: `What-if runs execute against ${sim}, and the UC-2 scenario `
        + 'studio computes its two scenarios in this browser from adapter data. '
        + 'The audited answers are the exception: they fetch figures from the '
        + 'shared UC-3 engine. No scenario run writes or persists anything.',
    },
    {
      tab: 'workflows',
      provenance: 'BROWSER',
      summary: 'Runs, approvals and the audit trail are held in this browser '
        + '(localStorage + BroadcastChannel). They do not survive a different machine, '
        + 'and the chain is editable from devtools — so it is a demonstration of the '
        + 'workflow, not audit evidence.',
    },
    {
      tab: 'models',
      provenance: 'STATIC',
      summary: 'Cards are transcribed from the exported model artefacts '
        + '(models/uc2/*/metrics.json). Live model health is probed separately and '
        + 'badged on the panel that uses each forecast.',
    },
    {
      tab: 'health',
      provenance: ctx.connectorsLive === null
        ? 'MIXED'
        : ctx.connectorsLive ? 'REAL' : 'SIMULATED',
      summary: ctx.connectorsLive === null
        ? 'Probing the six connector services…'
        : ctx.connectorsLive
          ? 'Health cards come from the connector services’ own /health endpoints.'
          : 'No connector service answered, so these cards are simulated in this browser.',
    },
    {
      tab: 'dataquality',
      provenance: poc3 ? 'REAL' : 'SIMULATED',
      summary: poc3
        ? `Findings from POC-3's core.dq_issue, raised against ${corpus}.`
        : `Cargo source is not POC-3, so findings come from ${sim}.`,
    },
    {
      tab: 'notifications',
      provenance: poc3 ? 'MIXED' : 'SIMULATED',
      summary: poc3
        ? 'A real stakeholder feed beside simulated operational alerts.'
        : `Everything on this tab comes from ${sim}.`,
      ...(poc3 ? {
        real: 'the POC-3 stakeholder notification feed',
        simulated: 'the role-filtered operational alert list',
      } : {}),
    },
    {
      tab: 'methodology',
      provenance: 'STATIC',
      summary: 'Written methodology, assumptions and known gaps. No data source.',
    },
  ];
}

export interface BoardSummary {
  /** The single word the header chip shows. */
  label: 'LIVE' | 'MIXED' | 'SIMULATED';
  real: number;
  mixed: number;
  simulated: number;
  /** Sentence for the chip's tooltip. */
  detail: string;
}

/**
 * Roll the per-screen map up into the one thing the header can fit.
 *
 * LIVE only when NOTHING is simulated — a single simulated screen makes the
 * board mixed, because a viewer who trusts the header on one tab will trust it
 * on all of them. STATIC screens (methodology, model cards) are excluded from
 * the count entirely: they are documents, and counting them either way would
 * move a number that describes data sources.
 */
export function boardSummary(screens: ScreenProvenance[]): BoardSummary {
  const counted = screens.filter((s) => s.provenance !== 'STATIC');
  const real = counted.filter((s) => s.provenance === 'REAL').length;
  const mixed = counted.filter((s) => s.provenance === 'MIXED').length;
  const simulated = counted.filter(
    (s) => s.provenance === 'SIMULATED' || s.provenance === 'BROWSER',
  ).length;

  const label: BoardSummary['label'] =
    real > 0 && mixed === 0 && simulated === 0 ? 'LIVE'
      : real === 0 && mixed === 0 ? 'SIMULATED'
        : 'MIXED';

  const parts = [
    real ? `${real} real` : '',
    mixed ? `${mixed} mixed` : '',
    simulated ? `${simulated} simulated` : '',
  ].filter(Boolean);

  return {
    label,
    real,
    mixed,
    simulated,
    detail: `${parts.join(' · ')} of ${counted.length} data screens. `
      + 'Every screen states its own source; click for the breakdown.',
  };
}

/**
 * What the KPI strip is entitled to claim (UC2-064, blocker B).
 *
 * The strip renders above every tab and, alone among the panels, carried no
 * provenance at all — seven tender-exact KPIs with nothing saying where they
 * came from. Derived from the guarded delegation list rather than written out,
 * so making `getKPIs` real (UC2-034/039) flips this line automatically instead
 * of leaving a stale "simulated" caption over real numbers.
 */
export const KPI_IS_SIMULATED: boolean =
  (SIMULATOR_BACKED_READS as readonly string[]).includes('getKPIs');

export const KPI_PROVENANCE: string = KPI_IS_SIMULATED
  ? 'Computed from the simulator dataset — not from the ingested corpus. '
    + 'Binding these to real events is UC2-034/039.'
  : 'Computed from the ingested corpus via POC-3.';

/** Colour role for a provenance, resolved by the caller against the theme. */
export function provenanceTone(p: Provenance): 'good' | 'warn' | 'muted' {
  if (p === 'REAL') return 'good';
  if (p === 'MIXED') return 'warn';
  return 'muted';
}
